### PR TITLE
Update Polish translation (24.12)

### PR DESCRIPTION
**Pull request by Gootector**
Update Polish translation (24.12)

Greetings,
Gootector

### CODE REVIEW

**Comment by Gootector** [comment]
@tedfelix Done.

**Comment by Gootector** [comment]
@tedfelix Should be (in the file header): "pl" or "pl_PL"?

**Comment by tedfelix** [comment]
> @tedfelix Should be (in the file header): "pl" or "pl_PL"?

No idea.  Looks like that's the direction all the others are headed.  Whatever works for you.

**Comment by Gootector** [comment]
> > @tedfelix Should be (in the file header): "pl" or "pl_PL"?
> 
> No idea. Looks like that's the direction all the others are headed. Whatever works for you.

OK. The "pl_PL" is added automatically by Qt Linguist app.
I think that's all. Ready to merge.

**Comment by Gootector** [comment]
@tedfelix Please merge 😉

**Comment by Gootector** [comment]
@tedfelix Please merge my PR. Thank you!

**Comment by tedfelix** [comment]
Thanks for the updates.  Will merge tomorrow in case you have any further tweaks you want to sneak in.

**Comment by Gootector** [comment]
@tedfelix Thanks.

**Pull request merged**
