### PR TITLE
Added ubuntu CI build

### PR DESCRIPTION
**Pull request by bownie**
A CI build for ubuntu might be of use? I'm looking at the possibility of creating an automated build of RG for windows so getting the ubuntu CI working this might be a nice first step :)

### CODE REVIEW

**Comment by bownie** [comment]
BTW I did want to squash these commits but couldn't see an option on creating the PR - hopefully (if you decide to use it) there's an option on the merge side..

**Comment by tedfelix** [comment]
I can squash anything you want squashed.  It just renders your branch potentially unmergeable (meaningless conflicts) when you resync.  You might have to reset your branch to master and continue.  Would be best to pursue when you get to a stopping point.

You can also delete your remote branch, squash selectively with rebase interactive locally then push the new branch.  (I believe github will not allow forced pushing rebased branches without deleting them first.)

Lots of options.

**Comment by bownie** [comment]
Slightly wider question is what's the source of truth for building RG now? Here or sourceforge? Is there any point committing this stuff here?

What I want to do now is be able to start adding #ifdef _WIN32/_WIN64 to rosegarden "upstream".  I've got a Windows and an Ubuntu CI now. Ubuntu works and could do with a package being built. Windows is green but doesn't do anything other than configure a build platform and get ready to Cmake.

**Comment by bownie** [comment]
Ok, great thanks! I've tidied up the commit history. Not sure if you want the README -> README.md change but thought as it's on github that might make more sense.

**Pull request merged**
