### PR TITLE
Update Translations

### PR DESCRIPTION
**Pull request by Gootector**
Update Translations

Greetings,
Gootector

### CODE REVIEW

**Comment by Gootector** [comment]
@tedfelix A few untranslated strings. Please merge.

**Comment by Gootector** [comment]
@tedfelix Done and squashed. I updated Polish translation and I fixed a typo in all files: "Rosgarden" to "Rosegarden".

**Comment by Gootector** [comment]
@tedfelix I fixed this typo in the entire code.

**Comment by Gootector** [comment]
@tedfelix Done and squashed again. In my opinion everything's fine now.

**Comment by Gootector** [comment]
@tedfelix I finished my work. Please merge my PR.

**Comment by tedfelix** [comment]
Done.  Thanks.

**Pull request merged**
