### PR TITLE
Update Polish Translation

### PR DESCRIPTION
**Pull request by Gootector**
Update Polish Translation

Greetings,
Gootector

### CODE REVIEW

**Comment by Gootector** [comment]
@tedfelix Done. Please merge.

**Comment by Gootector** [comment]
@tedfelix Should be fine now. Please merge.

**Comment by tedfelix** [comment]
Skimmed.  Looks great.  Thanks.  I learned some Polish.  I'll get this in.

Would love to have you maintain this in the future if you have the time.  I post translation reminders on the user mailing list one week prior to a new release going out.  You can subscribe here (it's not too noisy):

https://sourceforge.net/projects/rosegarden/lists/rosegarden-user

...or I can email you a reminder directly when we are about to do a release.  Let me know.

Dzięki!

**Comment by Gootector** [comment]
I subscribed to this mailing list. Two weeks prior to a new release would be a better option, but I'll do my best. Thank you!

**Comment by Gootector** [comment]
I'm translating also: MuseScore (and its fork: MuseScore Evolution), Audacity (and its forks: Tenacity and Sneedacity), and TuxGuitar. I need more time to translate them all. On time, of course. Two weeks sounds good.

**Pull request merged**
